Custom scrollbar colors
ampache/ampache pull request #2673
Opened 2020-12-30 00:25 UTC by mitchray

Custom scrollbar styling, before & after

![scrollbars](https://user-images.githubusercontent.com/5735900/103322242-7ba42380-4a91-11eb-8906-6ad056c72fec.jpg)

2020-12-30 13:38 UTC, AshotN commented on client/stylus/main.styl
> +* {
I do not believe you need `*` scope for standard.

2020-12-30 13:40 UTC, AshotN commented on client/stylus/main.styl
> +*::-webkit-scrollbar {
You do not need any scope for WebKit style.

2020-12-30 13:41 UTC, AshotN requested changes
Change the scoping for standard compliant to `body`, remove all scoping for webkit style.

2020-12-31 03:40 UTC, mitchray commented
On my Windows Firefox 84 the scrollbar-width isn't affecting anything unless its globally `*` , even if I apply it to the elements which have overflow. Could just be something weird on my end but I've left it for now.

2020-12-31 11:30 UTC, AshotN commented
> On my Windows Firefox 84 the scrollbar-width isn't affecting anything unless its globally `*` , even if I apply it to the elements which have overflow. Could just be something weird on my end but I've left it for now.

I think I noticed that as well. I’m pretty against scoping with `*`. So we should look into this before this gets merged. 

I do like the custom scroll bars.

2021-01-10 21:56 UTC, mitchray commented
If its a performance concern using the ```*``` then I'd say fear not, modern browsers handle it very well

https://www.telerik.com/blogs/css-tip-star-selector-not-that-bad
https://alistapart.com/article/axiomatic-css-and-lobotomized-owls/#section4

Alternatively I can look into 3rd party scrollbar replacements

2021-01-11 05:07 UTC, AshotN approved these changes

2021-01-11 05:08 UTC, AshotN commented
Maybe I have an irrational fear of the `*` selector. We can always revisit this once it becomes more standardized.

2021-01-11 05:08 UTC, merged

2021-01-12 13:52 UTC, kuzi-moto commented
I don't believe it's an irrational fear. I believe it is against general best practices not to use it. The biggest one being performance, since it gets every single element.

2021-01-13 02:15 UTC, AshotN commented
> I don't believe it's an irrational fear. I believe it is against general best practices not to use it. The biggest one being performance, since it gets every single element.

The articles he listed seemed to argue otherwise, I would like to dive deeper into it.